development:
  adapter: postgresql
  encoding: unicode
  database: kypsy_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: kypsy_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: kypsy_production
  pool: 5
  username:
  password:

